jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip3 install --user -r requirements.txt
      - run: mkdocs build
      - run: mkdocs gh-deploy --force